base: ghcr.io/vanilla-os/desktop:main

name: Mac Mini Home Assistant Vanilla Desktop Custom Image by haryp2309

labels:
  maintainer: haryp2309

args:
  DEBIAN_FRONTEND: noninteractive

runs:
- echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

modules:

- name: init-setup
  type: shell
  commands:
  - lpkg --unlock
  - apt-get update

- name:
  type: shell
  commands:
  - apt-get install apparmor cifs-utils curl dbus jq libglib2.0-bin lsb-release network-manager nfs-common systemd-journal-remote systemd-resolved udisks2 wget -y

- name: install-docker
  type: shell
  commands:
  - curl -fsSL get.docker.com | sh


- name: cleanup
  type: shell
  commands:
  - apt-get autoremove -y
  - apt-get clean
  - lpkg --lock
